name : geocoder
on: 
  workflow_dispatch

env:
  API : ${{vars.api}}

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        -   name: checkout
            uses: actions/checkout@v2
             
        -   name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirement.txt  
        -   name: Afficher adrress
            run: |
                geocoder.py
