name : deployement
on: 
  workflow_dispatch

env:
  API : ${{secrets.api}}

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
            uses: docker/login-action@v1
            ##Complete


            - name: Build and push Docker image
            uses: docker/build-push-action@v2
            ##Complete